name: CICDeploy
on:
  push:
    branches: [ main ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install NPM dependencies
        run: npm install
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ap-south-1
      - name: Deploy Next.js app
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/m0z6o0u5
          docker buildx build --platform=linux/amd64 -t sample-nextjs .
          docker tag sample-nextjs:latest public.ecr.aws/m0z6o0u5/sample-nextjs:latest
          docker push public.ecr.aws/m0z6o0u5/sample-nextjs:latest
          cd cdk
          cdk synth
          cdk deploy